# Generated by Django 5.2.1 on 2025-09-18 11:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['email'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='store_app_c_last_na_f7f3b0_idx',
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='store_app_c_phone_ea00ad_idx',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='username',
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='', max_length=255, unique=True, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator(message='Допустимы только русские буквы, пробелы и дефисы.', regex='^[а-яА-ЯёЁ\\s-]+$')], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator(message='Допустимы только русские буквы, пробелы и дефисы.', regex='^[а-яА-ЯёЁ\\s-]+$')], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Номер телефона должен содержать только цифры, пробелы и знак +', regex='^\\+?[0-9\\s-]+$')], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, message='Цена должна быть положительной')]),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['email'], name='store_app_c_email_c778e3_idx'),
        ),
    ]
