# Generated by Django 5.2.1 on 2025-07-17 12:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0002_favoriteproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='imail',
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=50, null=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, validators=[django.core.validators.RegexValidator(message='Допустимы русские буквы, цифры, пробелы и знаки .,-', regex='^[а-яА-ЯёЁ0-9\\s.,-]+$')], verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Допустимы только русские буквы, пробелы и дефисы.', regex='^[а-яА-ЯёЁ\\s-]+$')], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Допустимы только русские буквы, пробелы и дефисы.', regex='^[а-яА-ЯёЁ\\s-]+$')], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator(message='Допустимы только русские буквы, пробелы и дефисы.', regex='^[а-яА-ЯёЁ\\s-]+$')], verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Номер телефона должен содержать только цифры, пробелы и знак +', regex='^\\+?[0-9\\s-]+$')], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(help_text='Уникальный идентификатор пользователя (можно использовать латиницу)', max_length=50, unique=True, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='first_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Допустимы только русские буквы, пробелы и дефисы', regex='^[а-яА-ЯёЁ\\\\s-]+$')], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='last_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Допустимы только русские буквы, пробелы и дефисы', regex='^[а-яА-ЯёЁ\\\\s-]+$')], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator(message='Допустимы только русские буквы, пробелы и дефисы', regex='^[а-яА-ЯёЁ\\\\s-]+$')], verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Номер телефона должен содержать только цифры, пробелы и знак +', regex='^\\+?[0-9\\s-]+$')], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='store',
            name='address',
            field=models.TextField(blank=True, validators=[django.core.validators.RegexValidator(message='Допустимы русские буквы, цифры, пробелы и знаки .,-', regex='^[а-яА-ЯёЁ0-9\\s.,-]+$')], verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='Допустимы только русские буквы, пробелы и дефисы', regex='^[а-яА-ЯёЁ\\s-]+$')], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='Допустимы только русские буквы, пробелы и дефисы', regex='^[а-яА-ЯёЁ\\s-]+$')], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Логин может содержать русские/латинские буквы, цифры и @/./+/-/_', regex='^[а-яА-ЯёЁa-zA-Z0-9@.+-_]+$')]),
        ),
    ]
