# Generated by Django 5.2.1 on 2025-08-04 16:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0003_remove_customer_imail_customer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='external_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на товар'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение товара'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Логин может содержать русские/латинские буквы, цифры и @/./+/-/_', regex='^[а-яА-ЯёЁa-zA-Z0-9@.+\\-_\\s]+$')]),
        ),
    ]
