# Generated by Django 5.2.1 on 2025-09-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0003_customer_is_verified_customer_magic_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='external_url',
            field=models.URLField(blank=True, max_length=700, null=True, verbose_name='Ссылка на товар'),
        ),
    ]
