# Generated by Django 5.2.1 on 2025-10-01 10:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0004_alter_product_external_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40, verbose_name='Ключ сессии')),
                ('url', models.CharField(max_length=500, verbose_name='URL страницы')),
                ('referer', models.CharField(blank=True, max_length=500, null=True, verbose_name='Источник')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время посещения')),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='Длительность (сек)')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Просмотр страницы',
                'verbose_name_plural': 'Просмотры страниц',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['session_key', 'timestamp'], name='store_app_p_session_7102b5_idx'), models.Index(fields=['timestamp'], name='store_app_p_timesta_65c773_idx')],
            },
        ),
    ]
