# Generated by Django 5.2.1 on 2025-11-18 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0006_store_latitude_store_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], verbose_name='День недели')),
                ('opening_time', models.TimeField(blank=True, null=True, verbose_name='Время открытия')),
                ('closing_time', models.TimeField(blank=True, null=True, verbose_name='Время закрытия')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Выходной')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='store_app.store', verbose_name='Филиал')),
            ],
            options={
                'verbose_name': 'Режим работы',
                'verbose_name_plural': 'Режимы работы',
                'ordering': ['store', 'day_of_week'],
                'unique_together': {('store', 'day_of_week')},
            },
        ),
    ]
